### PR TITLE
CI/pipeline fixes

### LINKED ISSUE #10: Fix issues raised by moodle-plugin-ci
For example here... https://github.com/daledavies/moodle-tool_registrationrules/actions/runs/10813292679/job/29996978099?pr=4

There are numerous Moodle Code Checker and Moodle PHPDoc Checker errors.

### PR DESCRIPTION
**Pull request by phager-at**
Fixes #10 , #9

### CODE REVIEW

**Comment by daledavies** [comment]
Niiice

**Comment by phager-at** [comment]
MR is ready for review.
It focuses on the CI and pipeline fixes.
And I'm sorry, but it's gotten really enormous—I pity the reviewer by now. :grimacing:

**Comment by phager-at** [comment]
Maybe it's best reviewed commit-by-commit to stay manageable.

**Comment by daledavies** [comment]
Not a problem, thanks for this! As expected it conflicts with my recent changes in `main` but shouldn't be anything major.

**Comment by daledavies** [comment]
I'm doing it file by file at the minute, we'll see how that goes. I've been working on some changes ready for implementing scoring so would be nice to have this merged asap.

**Comment by daledavies** [comment]
Hah many of your TODOs I've started to address too, not created an issue for it as I got carried away but things like addressing the differences between rule_checker::get_messages() and get_validation_messages()

File: rules/hcaptcha/classes/rule.php
Comment (daledavies) [inline rules/hcaptcha/classes/rule.php:1]: Not sure what's going on here, has the whole file changed?

File: rules/hcaptcha/classes/rule.php [hunk 1]
```diff
@@ -1,90 +1,129 @@
...
+namespace registrationrule_hcaptcha;
+
+use coding_exception;
+use MoodleQuickForm;
+use stdClass;
+use tool_registrationrules\local\rule\configurable;
+use tool_registrationrules\local\rule_check_result;
+
+/**
+ * Reference implementation of a registration rule subplugin.
```
Comment (daledavies) [inline rules/hcaptcha/classes/rule.php]: Should probably be updated to explain what this plugin/class is?

File: rules/hcaptcha/lang/en/registrationrule_hcaptcha.php [hunk 2]
```diff
@@ -1,29 +1,32 @@
...
+// Moodle is distributed in the hope that it will be useful,
+// but WITHOUT ANY WARRANTY; without even the implied warranty of
+// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+// GNU General Public License for more details.
+//
+// You should have received a copy of the GNU General Public License
+// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.
+
+/**
+ * Strings for registrationrule_nope registration rule psublugin.
```
Comment (daledavies) [inline rules/hcaptcha/lang/en/registrationrule_hcaptcha.php]: Should be `registrationrule_hcaptcha`?

File: rules/hibp/classes/rule.php [hunk 3]
```diff
@@ -1,88 +1,116 @@
...
-// Moodle is distributed in the hope that it will be useful,
-// but WITHOUT ANY WARRANTY; without even the implied warranty of
-// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-// GNU General Public License for more details.
-//
-// You should have received a copy of the GNU General Public License
-// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.
-
-/**
- * Reference implementation of a registration rule subplugin.
```
Comment (daledavies) [inline rules/hibp/classes/rule.php:19]: Again maybe we can explain this is for Have I Been Pwnd, having said that I guess these are reference implementations

File: rules/hcaptcha/version.php
Comment (daledavies) [inline rules/hcaptcha/version.php:1]: Same as above, have you changed every line?

File: rules/limitdatetime/classes/rule.php [hunk 4]
```diff
@@ -1,54 +1,99 @@
...
+     *
+     * @return rule_check_result|null A rule_check_result object or null if check not applicable for this type.
+     */
+    public function pre_data_check(): ?rule_check_result {
+        $now = time();
+
+        /* A wizard is never late, nor is he early,
+         * he arrives precisely when he means to.
+         *
+         * Just like users don't.
```
Comment (daledavies) [inline rules/limitdatetime/classes/rule.php:78]: hehe :)

File: classes/local/rule_checker.php [hunk 5]
```diff
@@ -145,14 +214,23 @@ public function is_registration_allowed(): bool {
         return true;
     }
 
+    /**
+     * Return checks' resulting messages.
```
Comment (daledavies) [inline classes/local/rule_checker.php]: Can't work out if the apostrophe is correct here, might be better written as "Return the resulting messages from each check"?

File: classes/local/rule_checker.php [hunk 6]
```diff
@@ -161,20 +239,30 @@ public function get_messages(): array {
         return $messages;
     }
 
+    /**
+     * Return checks' aggregated messages to be displayed as validation errors.
```
Comment (daledavies) [inline classes/local/rule_checker.php]: Same here, maybe... "Return the aggregated messages from each check, to be displayed as validation errors."

File: classes/local/rule_checker.php [hunk 7]
```diff
@@ -186,8 +274,14 @@ public function get_validation_messages(): array {
         }
         return $messages;
     }
-    
-    public function add_error_field($mform) {
+
+    /**
+     * Inject a form element to append information about failed checks as validation errors to.
```
Comment (daledavies) [inline classes/local/rule_checker.php]: Maybe... "Inject a form element so we can append information about failed checks to it as validation errors."

File: classes/local/rule_settings.php [hunk 8]
```diff
@@ -31,30 +31,67 @@
...
+
         $form = new static($instancerecord->type, $instanceid);
         $form->set_data($instancerecord);
 
         return $form;
     }
 
+    /**
+     * The constructor function calls the abstract function definition() and it will then
+     * process and clean and attempt to validate incoming data.
```
Comment (daledavies) [inline classes/local/rule_settings.php]: Maybe... "process, clean and attempt to validate incoming data.

File: error.php [hunk 9]
```diff
@@ -14,6 +14,24 @@
 // You should have received a copy of the GNU General Public License
 // along with Moodle.  If not, see <https://www.gnu.org/licenses/>.
 
+/**
+ * Error page used to display specific information why the registration has been blocked.
```
Comment (daledavies) [inline error.php]: I think should be "specific information **about** why the"

File: rules/disposableemails/classes/local/list_manager.php [hunk 10]
```diff
@@ -36,6 +52,13 @@ public function __construct() {
         ];
     }
 
+    /**
+     * Returns array of blocked domains, not to be accepted as mail addresses' domains.
```
Comment (daledavies) [inline rules/disposableemails/classes/local/list_manager.php]: Maybe... "not to be accepted as user email address domains."

File: rules/limitdatetime/classes/rule.php [hunk 11]
```diff
@@ -1,54 +1,99 @@
...
+         * TODO: check timezone used in settings and maybe explain about used timezone as hint in UI?
```
Comment (daledavies) [inline rules/limitdatetime/classes/rule.php:79]: Oh gosh, are we limiting this to the server timezone, offsetting it to the site's timezone, head explodes!

**Comment by daledavies** [comment]
Looks good, nice work!

Just a few minor nitpicks really, I'm a native English speaker but my grasp of the English language is far from perfect so feel free to ignore.

**Comment by phager-at** [comment]
> Looks good, nice work!
> 
> Just a few minor nitpicks really, I'm a native English speaker but my grasp of the English language is far from perfect so feel free to ignore.

Looking forward to incorporating your feedback! My peak of comprehension of the English language lies about 20 years (± a few years) in the past, when I took the [FCE](https://cambridge.at/en/exams/b2-first) during school. :-)

I'll try to go through your nitpicks and rebase some time today! And if you've got any more nitpicks for me, feel free to add them too. I'm not the best in expressing things in an understandable way.

**Comment by daledavies** [comment]
I appear to have pressed a button and requested a new review from myself!

File: rules/hibp/classes/rule.php (hunk 3 above)
Comment (phager-at) [reply rules/hibp/classes/rule.php:19]: That old text is not in place anymore. The whole file contained wrong line endings, so every line changed unfortunately.

Comment (phager-at) [reply rules/hibp/classes/rule.php:19]: Current text is: `Registration rule restricting registrations based on data from HaveIBeenPwnd.`

File: rules/limitdatetime/classes/rule.php (hunk 4 above)
Comment (phager-at) [reply rules/limitdatetime/classes/rule.php:78]: I love the quote because I'm late all the time and had to add line 78 as I've read Hitchhickers Guide to the Galaxy recently. ;-)

File: rules/limitdatetime/classes/rule.php (hunk 11 above)
Comment (phager-at) [reply rules/limitdatetime/classes/rule.php:79]: We currently use Moodle forms API's `date_time_selector` Elements without explicit further configuration, defaulting to the server timezone.

It may be best if we also inject a descriptive text explaining that the server timezone is used and may hinting to the currently viewing users timezone if it differs from the server timezone.
That way every user configuring the rule could calculate the expected times correctly.

See: https://docs.moodle.org/dev/lib/formslib.php_Form_Definition#date_time_selector and https://github.com/daledavies/moodle-tool_registrationrules/pull/17/files/610a8c4d8f7b0a5daa5562f68a04ffdc377d3187#diff-25c3fcf165260c54f5428c0ed5824cdfbd6d74f405684ce1dc2ce1461048894eR61

**Comment by phager-at** [comment]
@daledavies I finally found time to implement your feedback and rebase the branch! So if all checks pass we're ready to follow up on your review!

Do you usually have the developer close the threads as soon as they're processed or do you let the reviewer close them?
We usually let the reviewer close them, so he/she has the chance to re-review the incorporated feedback too.

**Comment by daledavies** [comment]
Awesome, we've got a well defined process around gitlab but rarely use github internally. I think having the reviewer close the conversations would be closest, and then give some form of approval for the PR to be merged. 

As we use gitlab we're talking about merge requests but we'd normally have the developer proceed with the actual merge once the MR has been approved by the reviewer.

**Comment by daledavies** [comment]
All checks have passed!

File: rules/hibp/classes/rule.php (hunk 3 above)
Comment (daledavies) [reply rules/hibp/classes/rule.php:19]: Strange, I must have been going mad!

File: rules/limitdatetime/classes/rule.php (hunk 11 above)
Comment (daledavies) [reply rules/limitdatetime/classes/rule.php:79]: Let's raise a separate issue for this then as it requires some thought. We should do that for each of the TODO items.

**Comment by daledavies** [comment]
Having said the above about the reviewer merging, I went ahead and merged as I can now push my own changes :)

Thank you for all this :)
